//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eazly.CommonKit.Module.Template00.Server.Services {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ServerTemplateResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServerTemplateResources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Eazly.CommonKit.Module.Template00.Server.Services.ServerTemplateResources", typeof(ServerTemplateResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[Eazly.ConfigContents]&apos;) AND type in (N&apos;U&apos;))
        ///CREATE TABLE [dbo].[Eazly.ConfigContents](
        ///	[ModuleId] [int] NOT NULL,
        ///	[QueryID] [nvarchar](255) NOT NULL,
        ///	[IsCreate] [nchar](1) NOT NULL,
        ///    [IsUpdate] [nchar](1) NOT NULL,
        ///    [IsDelete] [nchar](1) NOT NULL,
        ///    [IsExport] [nchar](1) NOT NULL,
        ///	[TenantId] [int] NOT NULL,
        ///	[SiteId] [int] NOT NULL,
        ///	[CreatedBy] [nvarchar](256) NOT NULL,
        ///	[CreatedOn] [datetime2](7) NOT NULL[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TCreateConfigTable {
            get {
                return ResourceManager.GetString("TCreateConfigTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IF OBJECT_ID(&apos;USP_@EntityName_Condition&apos;, &apos;P&apos;) IS NULL
        ///	EXEC(N&apos;
        ///CREATE PROCEDURE USP_@EntityName_Condition
        ///AS
        ///BEGIN
        ///	SET NOCOUNT ON;
        ///
        ///	SELECT	CAST(DATEADD(DAY, -7, GETDATE()) AS DATE) DateFrom,
        ///			CAST(DATEADD(DAY, 0, GETDATE()) AS DATE) DateTo,
        ///			&apos;&apos;&apos;&apos; SearchValue
        ///
        ///END
        ///&apos;)
        ///GO과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TCreateProdecureCondition {
            get {
                return ResourceManager.GetString("TCreateProdecureCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IF OBJECT_ID(&apos;USP_@EntityName_@QueryId&apos;, &apos;P&apos;) IS NULL
        ///	EXEC(N&apos;
        ///CREATE PROCEDURE USP_@EntityName_@QueryId(
        ///	@TenantId	INT,
        ///	@SiteId		INT,
        ///	@UserId		NVARCHAR(256),
        ///	@JsonParam	NVARCHAR(4000)
        ///)
        ///AS
        ///BEGIN
        ///	SET NOCOUNT ON;
        ///
        ///	DECLARE @dateFrom		DATETIME2(7),
        ///			@dateTo			DATETIME2(7),
        ///			@searchValue	NVARCHAR(256);
        ///
        ///	SELECT	@dateFrom		= MAX(CASE WHEN [KEY] = &apos;&apos;DateFrom&apos;&apos;	THEN [value] ELSE NULL END),
        ///			@dateTo			= MAX(CASE WHEN [KEY] = &apos;&apos;DateTo&apos;&apos;		THEN [value] ELSE NULL END),
        ///			@searchValue	= MA[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TCreateProdecureGetContents {
            get {
                return ResourceManager.GetString("TCreateProdecureGetContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IF OBJECT_ID(&apos;USP_@EntityName_Save_Pre&apos;, &apos;P&apos;) IS NULL
        ///	EXEC(N&apos;
        ///CREATE PROCEDURE USP_@EntityName_Save_Pre(
        ///	@TenantId	INT,
        ///	@SiteId		INT,
        ///	@UserId		NVARCHAR(256),
        ///	@JsonParam	NVARCHAR(4000)
        ///)
        ///AS
        ///BEGIN
        ///	SET NOCOUNT ON;
        ///
        ///    -- TODO: 구현
        ///
        ///    -- SELECT * FROM OPENJSON(@JsonParam)
        ///
        ///	-- 본 저장 프로시저 실행 필요 없으면 RERUN 9
        ///	-- RETURN 9
        ///
        ///    RETURN 1;
        ///END
        ///&apos;)
        ///GO
        ///
        ///IF OBJECT_ID(&apos;USP_@EntityName_Save_Post&apos;, &apos;P&apos;) IS NULL
        ///	EXEC(N&apos;
        ///CREATE PROCEDURE USP_@EntityName_Save_Post(
        ///	@TenantId	INT,
        ///	@SiteId		I[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TCreateProdecureSaveContents {
            get {
                return ResourceManager.GetString("TCreateProdecureSaveContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IF  NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[@TableName]&apos;) AND type in (N&apos;U&apos;))
        ///CREATE TABLE [dbo].[@TableName](
        ///	[TId] [int] IDENTITY(1,1) NOT NULL,
        ///	[Desc] [nvarchar](255) NULL,
        ///
        ///	[TenantId] [int] NOT NULL,
        ///	[SiteId] [int] NOT NULL,
        ///	[CreatedBy] [nvarchar](256) NOT NULL,
        ///	[CreatedOn] [datetime2](7) NOT NULL,
        ///	[ModifiedBy] [nvarchar](256) NOT NULL,
        ///	[ModifiedOn] [datetime2](7) NOT NULL,
        /// CONSTRAINT [PK_@TableName] PRIMARY KEY CLUSTERED 
        ///(
        ///	[TId] ASC
        ///)WITH (PAD[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TCreateTable {
            get {
                return ResourceManager.GetString("TCreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EXEC USP_@EntityName_Save @TenantId, @SiteId, N&apos;@UserId&apos;, N&apos;@JsonParam&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TExecuteQueryID {
            get {
                return ResourceManager.GetString("TExecuteQueryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EXEC USP_@EntityName_Condition과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TGetCondition {
            get {
                return ResourceManager.GetString("TGetCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   SELECT [IsCreate], [IsUpdate], [IsDelete], [IsExport]
        ///  FROM [dbo].[Eazly.ConfigContents] (NOLOCK)
        ///WHERE TenantId = @TenantId AND SiteId = @SiteId AND ModuleId = @ModuleId AND QueryID = &apos;@QueryId&apos;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TGetConfigContents {
            get {
                return ResourceManager.GetString("TGetConfigContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TGetConfigContentsColumns {
            get {
                return ResourceManager.GetString("TGetConfigContentsColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EXEC USP_@EntityName_@QueryId @TenantId, @SiteId, N&apos;@UserId&apos;, N&apos;@JsonParam&apos;
        ///과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TGetContentsID {
            get {
                return ResourceManager.GetString("TGetContentsID", resourceCulture);
            }
        }
    }
}
