<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>1.0.0</Version>
    <Authors>Eazly.CommonKit</Authors>
    <Company>Eazly.CommonKit</Company>
    <Description>Template00</Description>
    <Product>Eazly.CommonKit.Module.Template00</Product>
    <Copyright>Eazly.CommonKit</Copyright>
    <AssemblyName>Eazly.CommonKit.Module.Template00.Client.Oqtane</AssemblyName>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.3" />
    <PackageReference Include="Radzen.Blazor" Version="10.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\Eazly.CommonKit.Module.Template00.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Oqtane.Client" Version="10.1.1" />
    <PackageReference Include="Oqtane.Shared" Version="10.1.1" />
  </ItemGroup>

  <PropertyGroup>
    <!-- there may be other elements here -->
    <BlazorWebAssemblyEnableLinking>false</BlazorWebAssemblyEnableLinking>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
